name: periodic

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '17 14 * * 4'

jobs:
  analyze:
    name: analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install deps with apt-get
      run : |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends  \
          libgl1-mesa-dev  \
          libglu1-mesa-dev  \
          mesa-common-dev  \
          xorg-dev

    - name: initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: autobuild
      uses: github/codeql-action/autobuild@v1

    - name: perform analysis
      uses: github/codeql-action/analyze@v1

